---
- hosts: webservers # TODO
  vars:
     # name,password,uid,group
     csvfile: "{{ lookup('file', '/home/prueba/ansible_testing/testdir/userlist.csv') }}"
     lines: "{{ csvfile.split('\n') }}"

  tasks:  
  - name: create users
    become: yes
    become_user: root
    user:
     name: "{{item.split(',')[0]}}"
     password: "{{item.split(',')[1]}}"
     uid: "{{item.split(',')[2]}}"
     group: "{{item.split(',')[3]}}"
    with_items: 
     - "{{lines}}"